### ISSUE TITLE
1.2.0 Checklist

### ISSUE THREAD

**Issue by mac-r** [blinkloader/react-blinkloader-components#1]
- [ ] minimize the amount of event listeners for lazyloading (remove listeners when image is loaded, don’t listen every image, maybe even add invisible blocks for the whole length of the page)

- [ ] add an optional rendering mode, when images are applied as a background

- [ ] estimate FPS on the apple website and reach same FPS on pages with our integration (especially on scrolling)

- [ ] start loading images for the page even before the react bundle is loaded (in case SSR already returns html markup)

- [ ] make sure that there are no conflicts when client-side bundle is loaded

- [ ] provide configuration via header instead of the provider

- [ ] ideally: figure out how to add blinkloader inline into head or body bottom (very tricky with react and next.js)

- [ ] make sure that library is applied on each page even with react router and next.js magic

- [ ] cover big amount of edge cases (long pages with images, all cases from the common website)

- [ ] make sure that there are no race conditions with blurry svgs and normal images (normal images should never be replaces with svg)

- [ ] load blurry svg and normal image in parallel, but keep in mind the race condition

- [ ] make lazyloading smarter, if all visible area is loaded, then load next upcoming images

- [ ] add client side support for the react integration, doesn’t work without SSR (ASAP)
